# Generated by Django 3.2.8 on 2021-10-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=64)),
                ('Task_Description', models.CharField(max_length=256)),
                ('Task_Type', models.CharField(max_length=256)),
                ('Task_Grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Due_Date', models.DateField()),
            ],
        ),
    ]
