# Generated by Django 3.2.8 on 2021-12-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Task_Type',
            field=models.CharField(choices=[('MJ', 'Major'), ('MN', 'Minor'), ('PRJ', 'Project')], max_length=256),
        ),
    ]
