# Generated by Django 3.2.8 on 2021-12-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_App', '0002_alter_tasks_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Due_Date',
            field=models.DateTimeField(),
        ),
    ]
